name: Run Java GUI

on: [push]

jobs:
  run-java:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Xvfb
        run: sudo apt-get install xvfb

      - name: Start Virtual Display
        run: Xvfb :99 &

      - name: Set Display Environment
        run: export DISPLAY=:99

      - name: Compile Java Code
        run: javac Login.java

      - name: Run Java GUI Program
        run: java Login
